@startuml Dateivergleich_Prompt
salt
{
{+
. | .
 <size:14> File comparison for "filename"</size>
. | .
{^"Input (Before Merge)"
 . | .| .| .| .| .
 . | .| .| .| .| .
.| .{+
.| . 
.| .{+
 . | .| .| .| .| .
 . | .
 .| .| .| .| . | CURRENT | .| .| .| .| .
 . | .
 . | .

} .| .|.| . {+
 . | .| .| .| .| .
 . | .
 .| .| .| .| . | PREVIOUS | .| .| .| .| .
 . | .
 . | .
} .| .
.| .
}
.| .
}

{^"Prompt (After Merge)"
 . | .| .| .| .| .
 . | .| .| .| .| .
.| .{+
.| . 
.| .{+
 . | .| .| .| .| .
 . | .
 .| .| .| .| . | CURRENT | .| .| .| .| .
 . | .
 . | .

} .| .|.| . {+
 . | .| .| .| .| .
 . | .
 .| .| .| .| . | PREVIOUS | .| .| .| .| .
 . | .
 . | .
} .| .
.| .
}
.| .
}

{^"Reply"
 . | .| .| .| .| .
 . | .| .| .| .| .
.| .{+
.| . 
.| .{+
 . | .| .| .| .| .
 . | .
 .| .| .| .| . | CURRENT | .| .| .| .| .
 . | .
 . | .

} .| .|.| . {+
 . | .| .| .| .| .
 . | .
 .| .| .| .| . | PREVIOUS | .| .| .| .| .
 . | .
 . | .
} .| .
.| .
}
.| .
}
{ INCLUDED FILES }
{
 . | <b>Filename</b>                | . | . | <b>Status</b>  | . | . 
 . | <i>FirstIncludedFile.java</i>  | . | . | <b>CHANGED</b> | . | . 
 . | <i>SecondIncludedFile.java</i> | . | . | .              | . | .  
}

}

}

}
@enduml
